package com.veertu.plugin.anka;

import com.cloudbees.plugins.credentials.CredentialsScope;
import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class AnkaUakTapCredentialsTest {

    @Test
    public void constructorReplacesAutoGeneratedDescriptionAndId() {
        AnkaUakTapCredentials credentials = new AnkaUakTapCredentials(
                CredentialsScope.GLOBAL,
                "index-0",
                "index-1",
                "uak-id",
                "uak-secret");

        assertThat(credentials.getId(), is("anka-build-cloud-plugin-uak-tap-authentication"));
        assertThat(credentials.getDescription(), is(AnkaCredentialNaming.PREFIX + "UAK/TAP Authentication"));
        assertThat(credentials.getUsername(), is("uak-id"));
    }

    @Test
    public void constructorPrefixesCustomDescription() {
        AnkaUakTapCredentials credentials = new AnkaUakTapCredentials(
                CredentialsScope.GLOBAL,
                "anka-uak",
                "Production Controller",
                "uak-id",
                "uak-secret");

        assertThat(credentials.getId(), is("anka-uak"));
        assertThat(credentials.getDescription(), is(AnkaCredentialNaming.PREFIX + "Production Controller"));
    }
}
