package com.veertu.plugin.anka;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.not;

public class AnkaCredentialNamingTest {

    @Test
    public void normalizeIdReplacesAutoGeneratedLabelsWithSlug() {
        String normalizedId = AnkaCredentialNaming.normalizeId(
                "index-0",
                AnkaCredentialNaming.PREFIX + "Certificate Authentication");

        assertThat(normalizedId, is("anka-build-cloud-plugin-certificate-authentication"));
    }

    @Test
    public void normalizeIdPreservesUserProvidedId() {
        assertThat(AnkaCredentialNaming.normalizeId("anka-controller-mtls", null), is("anka-controller-mtls"));
    }

    @Test
    public void normalizeIdReplacesAutoGeneratedLabelsWithoutLabel() {
        String normalizedId = AnkaCredentialNaming.normalizeId("index-0");

        assertThat(normalizedId, not("index-0"));
        assertThat(normalizedId.isEmpty(), is(false));
    }

    @Test
    public void normalizeLabelPrefixesCustomNames() {
        assertThat(
                AnkaCredentialNaming.normalizeLabel("Production Controller", "Certificate Authentication"),
                is(AnkaCredentialNaming.PREFIX + "Production Controller"));
    }

    @Test
    public void normalizeLabelReplacesAutoGeneratedNames() {
        assertThat(
                AnkaCredentialNaming.normalizeLabel("index-1", "UAK/TAP Authentication"),
                is(AnkaCredentialNaming.PREFIX + "UAK/TAP Authentication"));
    }

    @Test
    public void normalizeLabelPreservesExistingPrefix() {
        assertThat(
                AnkaCredentialNaming.normalizeLabel(
                        AnkaCredentialNaming.PREFIX + "Existing",
                        "Certificate Authentication"),
                is(AnkaCredentialNaming.PREFIX + "Existing"));
    }
}
