package com.veertu.plugin.anka;

import com.cloudbees.plugins.credentials.CredentialsScope;
import com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.jvnet.hudson.test.JenkinsRule;
import org.jvnet.hudson.test.junit.jupiter.WithJenkins;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.instanceOf;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.sameInstance;
import static org.hamcrest.Matchers.startsWith;

@WithJenkins
public class CertCredentialsTest {

    private JenkinsRule jenkinsRule;

    @BeforeEach
    void setUp(JenkinsRule jenkinsRule) {
        this.jenkinsRule = jenkinsRule;
    }

    @Test
    public void constructorReplacesAutoGeneratedNameAndId() {
        CertCredentials credentials = new CertCredentials(
                CredentialsScope.GLOBAL,
                "index-0",
                "index-1",
                "index-2",
                "key",
                "cert");

        assertThat(credentials.getId(), is("anka-build-cloud-plugin-certificate-authentication"));
        assertThat(credentials.getName(), is(AnkaCredentialNaming.PREFIX + "Certificate Authentication"));
        assertThat(credentials.getDescription(), is(AnkaCredentialNaming.PREFIX + "Certificate Authentication"));
    }

    @Test
    public void implementsIdCredentialsSoCredentialsUiUsesConfiguredId() {
        CertCredentials credentials = new CertCredentials(
                CredentialsScope.GLOBAL,
                "anka-controller-mtls",
                "Production Controller",
                "Production Controller mTLS",
                "key",
                "cert");

        assertThat(credentials, instanceOf(com.cloudbees.plugins.credentials.common.IdCredentials.class));
        assertThat(((com.cloudbees.plugins.credentials.common.IdCredentials) credentials).getId(), is("anka-controller-mtls"));
    }

    @Test
    public void constructorPrefixesCustomName() {
        CertCredentials credentials = new CertCredentials(
                CredentialsScope.GLOBAL,
                "anka-cert",
                "Production Controller",
                "Production Controller mTLS",
                "key",
                "cert");

        assertThat(credentials.getId(), is("anka-cert"));
        assertThat(credentials.getName(), is(AnkaCredentialNaming.PREFIX + "Production Controller"));
        assertThat(credentials.getDescription(), startsWith(AnkaCredentialNaming.PREFIX));
    }

    @Test
    public void getDescriptorReturnsExtensionSingleton() {
        CertCredentials credentials = new CertCredentials(
                CredentialsScope.GLOBAL,
                "anka-cert",
                "Production",
                "Production mTLS",
                "key",
                "cert");

        assertThat(
                credentials.getDescriptor(),
                sameInstance(jenkinsRule.jenkins.getDescriptorByType(CertCredentials.DescriptorImpl.class)));
    }
}
