package com.veertu.plugin.anka;

import com.cloudbees.plugins.credentials.common.IdCredentials;
import hudson.Util;

import java.util.Locale;
import java.util.regex.Pattern;

final class AnkaCredentialNaming {

    static final String PREFIX = "Anka Build Cloud Plugin: ";

    private static final Pattern AUTO_GENERATED_LABEL = Pattern.compile("index-\\d+");

    private AnkaCredentialNaming() {
    }

    static boolean isAutoGeneratedLabel(String value) {
        return value != null && AUTO_GENERATED_LABEL.matcher(value).matches();
    }

    static String normalizeId(String id) {
        return normalizeId(id, null);
    }

    static String normalizeId(String id, String preferredLabel) {
        String trimmedId = Util.fixEmptyAndTrim(id);
        if (trimmedId != null && !isAutoGeneratedLabel(trimmedId)) {
            return trimmedId;
        }

        String slugFromLabel = slugifyId(preferredLabel);
        if (slugFromLabel != null) {
            return slugFromLabel;
        }

        return IdCredentials.Helpers.fixEmptyId(null);
    }

    private static String slugifyId(String label) {
        String trimmed = Util.fixEmptyAndTrim(label);
        if (trimmed == null || isAutoGeneratedLabel(trimmed)) {
            return null;
        }

        String slug = trimmed.toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9_.-]+", "-")
                .replaceAll("-+", "-")
                .replaceAll("^[-_.]+|[-_.]+$", "");

        return slug.isEmpty() ? null : slug;
    }

    static String normalizeLabel(String label, String defaultSuffix) {
        String trimmed = Util.fixEmptyAndTrim(label);
        if (trimmed == null || isAutoGeneratedLabel(trimmed)) {
            return PREFIX + defaultSuffix;
        }
        if (trimmed.startsWith(PREFIX)) {
            return trimmed;
        }
        return PREFIX + trimmed;
    }

    static String displayLabel(String label, String defaultSuffix) {
        String trimmed = Util.fixEmptyAndTrim(label);
        if (trimmed == null || isAutoGeneratedLabel(trimmed)) {
            return PREFIX + defaultSuffix;
        }
        return trimmed;
    }
}
