
version: '2'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: jenkins
    volumes:
      - /data/jenkins:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
      JAVA_OPTS: "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=5005,suspend=n -Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.main.modules.sshd.SSHD.hostName=127.0.0.1 -Dorg.jenkinsci.main.modules.sshd.SSHD.port=5000 -Djenkins.CLI.disabled=false -Dorg.jenkinsci.main.modules.sshd.SSHD.mode=fixed"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
      - "5005:5005"
