properties(
    [
        buildDiscarder(
            logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '1')
        ), 
        disableConcurrentBuilds(), 
        disableResume(), 
        copyArtifactPermission('*'), 
        durabilityHint('PERFORMANCE_OPTIMIZED')
    ]
)
pipeline {
    agent { dockerfile {
        filename 'Dockerfile'
        dir '_ci'
        label 'poweredge'
        reuseNode true
        args "--name ${env.JOB_NAME.replace('%2F', '_').replace('/', '_')}-${env.BUILD_NUMBER}"
    } }
    stages {
        stage('Build Plugin') { steps {
            sh 'mvn package'
        } }
        stage('Archive') { steps {
            archiveArtifacts artifacts: '**/target/anka-build.hpi', onlyIfSuccessful: true
        } }
    }
}